### ISSUE TITLE
How to extract the co-author information from DBLP?

### ISSUE THREAD

**Issue by liudonglei** [yuchenhao/coauthor-vis#1]
你好，我对这个可视化展示很感兴趣，我想做个在数据库领域的类似展示。

我大致浏览了一些文件，发现诸如作者名等数据的在那个data.json文件里，但是我想知道你们是如何构建和生成这个data.json的，就是如何从dblp的那个大xml文件如何生成这个repo里的data.json？

**Comment by yuchenhao** [comment]
Hi,

We didn't convert the xml to json directly. We actually parsed the xml into csv for manipulation using R and then the visualization tool did the job converting csv to json for us. 

If you are asking about xml parsers, I suggest you look at common xml parser libraries in the language you feel comfortable with. For example, xml.sax is what we use in python which is pretty straightforward. If you are asking about json builders, it is even simpler. Most languages support it in their standard library.

**Comment by liudonglei** [comment]
多谢，我想找的就是那个xml parser，我去试试xml.sax.
